# Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License

AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template configures a VPC and cloud9 instance. 

Resources:

  ModernizationVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://modernization-workshop-bucket.s3-us-west-2.amazonaws.com/cfn/vpc/vpc.yaml
      Parameters:
        EnvironmentName: Workshop
    
  ModernizationCloud9:
    DependsOn: ModernizationVPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://modernization-workshop-bucket.s3-us-west-2.amazonaws.com/cfn/cloud9/cloud9.yaml
      Parameters:
        PublicSubnet1: !GetAtt ModernizationVPC.Outputs.PublicSubnet1

Outputs: {}